name: upgrade-proxy

on:
  schedule:
  - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Upgrade
        run: go get -u github.com/HimbeerserverDE/mt-multiserver-proxy

      - uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
            -tools/go.mod
