name: upgrade-proxy

on:
  repository_dispatch:

jobs:
  upgrade_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      - name: Install mt-build-plugin
        env:
          PROXYVER: ${{ github.event.client_payload.proxy_version }}
        run: |
          go install github.com/HimbeerserverDE/mt-multiserver-proxy/cmd/mt-build-plugin@${PROXYVER}

      - name: Upgrade and verify build success
        run: |
          mt-build-plugin

      - name: Add, commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add go.mod go.sum
          git commit -m "auto-upgrade proxy"
          git push
        continue-on-error: true
