name: upgrade-proxy

on:
  schedule:
  - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  upgrade_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Upgrade and tidy
        run: |
          go get -u github.com/HimbeerserverDE/mt-multiserver-proxy
          go mod tidy

      - name: Add, commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add go.mod go.sum
          git commit -m "Upgrade proxy"
          git push
